#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate Emoji.js (used by the Quickshell conversation window) from the
Python shortcode/emoticon tables, so the two never drift. Run after editing
lib/omarchy_signal/emoji.py; tests/python/test_emoji.py checks the result."""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "lib"))
from omarchy_signal import emoji  # noqa: E402

HEADER = """// SPDX-License-Identifier: GPL-3.0-or-later
// GENERATED by scripts/gen_emoji_js.py from lib/omarchy_signal/emoji.py. Do not edit.
// Shortcodes (:smile:) and emoticons (:D) for the conversation window's composer.

var SHORTCODES = %s
var EMOTICONS = %s

function lookup(code) {
  var v = SHORTCODES[String(code || "").toLowerCase()]
  return v === undefined ? null : v
}

// After a space was typed: convert the word before it if it is a known
// :code: or a standalone emoticon. Returns {text, cursor} or null.
function convertBeforeCursor(text, cursor) {
  if (typeof text !== "string" || cursor < 2 || cursor > text.length || text.charAt(cursor - 1) !== " ") return null
  var head = text.substring(0, cursor - 1)
  var start = Math.max(head.lastIndexOf(" "), head.lastIndexOf("\\n")) + 1
  var token = head.substring(start)
  if (!token) return null
  var glyph = null
  var m = /^:([A-Za-z0-9_+\\-]{1,40}):$/.exec(token)
  if (m) glyph = lookup(m[1])
  else if (Object.prototype.hasOwnProperty.call(EMOTICONS, token)) glyph = EMOTICONS[token]
  if (!glyph) return null
  var out = text.substring(0, start) + glyph + " " + text.substring(cursor)
  return { text: out, cursor: start + glyph.length + 1 }
}

if (typeof module !== "undefined") module.exports = { SHORTCODES: SHORTCODES, EMOTICONS: EMOTICONS, lookup: lookup, convertBeforeCursor: convertBeforeCursor }
"""


def render() -> str:
    return HEADER % (json.dumps(emoji.SHORTCODES, ensure_ascii=False, indent=0, sort_keys=True),
                     json.dumps(emoji.EMOTICONS, ensure_ascii=False, indent=0, sort_keys=True))


if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "..", "Emoji.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(render())
    print("wrote", os.path.normpath(out))
